### ISSUE TITLE
Configurable page title

### ISSUE THREAD

**Issue by jbelien** [openknowledgebe/website#38]
The about page uses the title defined in the CMS.

```js
<Header>
  <Title as="h1">{data.seo?.title}</Title>
</Header>
```
https://github.com/openknowledgebe/website/blob/main/src/pages/about.js#L31

It should be the same for ALL the pages (team, activities, stories) ; currently the page title is hardcoded and not using the title defined in the CMS.

```js
<Title as="h1" css="margin-bottom: 3rem;">
  Our <br />
  activities
</Title>
```
https://github.com/openknowledgebe/website/blob/main/src/pages/activities.js#L42-L45

```js
<Title as="h1">
  Our <br />
  stories
</Title>
```
https://github.com/openknowledgebe/website/blob/main/src/pages/stories.js#L28-L31

```js
<Title as="h1">
  Our <br />
  Team
</Title>
```
https://github.com/openknowledgebe/website/blob/main/src/pages/team.js#L138-L141

Styling should also be the same (see `css="margin-bottom: 3rem;"` for activities page) !

**Comment by auloin** [comment]
The issue here is that some of the titles are on 2 lines (`<br />`).

- We may assume that every title will break into (max) 2 lines and use `JS` to make it happen
- or that the width is so small that every word will create a newline
- or that users will take care of breaking titles and provide them with a minimal markdown widget
- or ...

The current assumption is that these titles won't change too often.

**Comment by jbelien** [comment]
To be honest, I don't see the reason behind the `<br />` between the 2 words ...

Couldn't we just display the title (they are rather small anyway) without any formatting ?

**Comment by jbelien** [comment]
The "issue" with the `<br />` is not existent anymore since all titles have been updated (see https://github.com/openknowledgebe/website/issues/61#issuecomment-747997880).

You can move forward with this request and make all titles configurable. 👍
